version: '2.3'
services:
  api:
    container_name: search-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    image: search-fastapi:base
    ports:
      - "8003:8003"
    volumes:
      - ./app:/server/app
      - ./entrypoint.sh:/server/entrypoint.sh
      - ./main.py:/server/main.py
      - ./corpus_files/DidYouMean:/server/DidYouMean
      - ./corpus_files/QuerySuggestor:/server/QuerySuggestor
      - ./corpus_files/SpellChecker:/server/SpellChecker
    command: server
    env_file:
      - .env
    mem_limit: 8g
    privileged: true
    networks:
      - demo-networks

networks:
  demo-networks:
    external: false
