version: '2.3'
services:
  api:
    container_name: search-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    image: search-fastapi:base
    ports:
      - "8003:8003"
    command: server
    env_file:
      - .env
    mem_limit: 8g
    privileged: true
    networks:
      - demo-networks

networks:
  demo-networks:
    external: false
